blank_issues_enabled: true
contact_links:
  - name: Get Help
    url: https://github.com/your-username/your-repository/discussions/new?category=q-a
    about: If you encounter any issues while using the project, please ask for help here.
  - name: GitHub Discussions
    url: https://github.com/your-username/your-repository/discussions
    about: This is a discussion area where you can ask questions, share ideas, or have general discussions unrelated to bugs or features.

issue_templates:
  - name: Bug Report
    description: Found a bug? Help us fix it!
    link: .github/ISSUE_TEMPLATE/bug_report.md
  - name: Feature Request
    description: Suggest a new feature or an improvement to an existing one.
    link: .github/ISSUE_TEMPLATE/feature_request.md
  - name: New Use Case Request
    description:
      💡 Propose a new use or application area for a product or feature.
    labels: ["enhancement", "new-use-case-request"]
    assignees: [] # Who to assign by default, can be left blank
    body:
      - type: markdown
        attributes:
          value: |
            ## ✨ New Use Case Overview

            Please briefly describe the new use case or application area you would like us to support. For example, "I want Software A to also solve Problem B."

            ## 📚 Connection Between Existing Features and New Use Case

            Do current products/features already have some capabilities that could support this new use case? If so, please explain.

            ## 🎯 Value and Target Users of the New Use Case

            - **What problem does this new use case solve?** What benefits does it bring to users?
            - **Who are the primary target users?** For which groups is this use case particularly valuable?

            ## 💡 Detailed Description and Implementation Ideas (Optional)

            Please describe the user experience, workflow, or specific implementation details of this new use case as thoroughly as possible.
            (e.g., if possible, provide steps, examples, pseudocode, or conceptual diagrams.)

            ## 📈 Expected Impact and Metrics (Optional)

            If this new use case is implemented, what positive impacts do you anticipate? How can we measure its success?

            ## 🤔 Potential Challenges or Considerations (Optional)

            What technical or non-technical challenges do you foresee when implementing this new use case?

            ---
            Thank you for your valuable suggestions! We appreciate every voice from the community.
