name: "🐛 Bug Report"
description: "Report a bug encountered while using Mori"
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reporting a bug! 🐛
        
        Please provide as much information as possible to help us understand and fix the issue quickly. 
        A well-detailed bug report saves time for both developers and users looking for solutions.
        
        **Please DO NOT use this template to ask questions.** Use [Discussions](https://github.com/aquarius-wing/mori/discussions) for questions.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      description: "Please confirm the following before submitting your bug report:"
      options:
        - label: "I have searched [existing issues](https://github.com/aquarius-wing/mori/issues) and found no similar reports"
          required: true
        - label: "I have read the documentation and troubleshooting guides"
          required: true
        - label: "I can reproduce this bug consistently"
          required: true

  - type: textarea
    id: bug-summary
    attributes:
      label: "Bug Summary"
      description: "Provide a clear and concise description of the bug."
      placeholder: "A brief summary of what went wrong..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity Level"
      description: "How severe is this bug?"
      options:
        - "Critical - App crashes or data loss"
        - "High - Major feature doesn't work"
        - "Medium - Minor feature issue or workaround exists"
        - "Low - Cosmetic issue or minor inconvenience"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps to reproduce the bug."
      placeholder: |
        1. Open the app
        2. Navigate to '...'
        3. Tap on '...'
        4. Observe the bug
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What should have happened instead?"
      placeholder: "I expected the app to..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Instead, the app..."
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: "How often does this bug occur?"
      description: "Select the frequency of this bug"
      options:
        - "Always (100%)"
        - "Often (75-99%)"
        - "Sometimes (25-74%)"
        - "Rarely (1-24%)"
        - "Once"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment Information"
      description: "Please provide detailed information about your environment."
      placeholder: |
        **Device:** iPhone 14 Pro / iPad Air / Mac Studio
        **OS Version:** iOS 17.1 / iPadOS 17.1 / macOS 14.1
        **App Version:** v1.0.0 (Build 123)
        **Installation Method:** App Store / TestFlight / Xcode
      value: |
        **Device:** 
        **OS Version:** 
        **App Version:** 
        **Installation Method:** 
    validations:
      required: true

  - type: textarea
    id: screenshots-videos
    attributes:
      label: "Screenshots / Videos"
      description: "If applicable, add screenshots or screen recordings to help explain the problem."
      placeholder: "Drag and drop images/videos here or paste links..."
    validations:
      required: false

  - type: textarea
    id: logs-console
    attributes:
      label: "Console Logs / Error Messages"
      description: "If you have access to console logs or error messages, please include them here."
      placeholder: "Paste any error messages or log output here..."
      render: shell
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: "Workaround (if any)"
      description: "Have you found any temporary solution or workaround?"
      placeholder: "I can work around this by..."
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: "Impact Assessment"
      description: "How does this bug affect your usage?"
      options:
        - label: "Prevents me from using the app"
        - label: "Significantly impacts my workflow"
        - label: "Minor inconvenience"
        - label: "Doesn't affect core functionality"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      placeholder: "Any additional information that might help us understand the issue..."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: "Contribution"
      description: "Are you willing to help with this bug?"
      options:
        - label: "I'm willing to submit a PR to fix this bug"
        - label: "I can help with testing the fix"
        - label: "I can provide more information if needed"